from ...gerarDados import umDiaAposHoje, trintaUmDiasAposHoje
from playwright.sync_api import expect, Page

# Page Object para seleção de formas de pagamento no processo de recebimento.
class Receipt:
    def __init__(self, page: Page):
        self.page = page

    # Seleciona forma de pagamento 3860 (T.A. A Receber Futuro)
    def main(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        forma_pagamento = self.page.locator('[style=""] > md-collapsible-header.layout-row > .md-collapsible-tools > .ng-scope')
        expect(forma_pagamento).to_be_visible()
        expect(forma_pagamento).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        forma_pagamento.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3862 (T.A.A Receber CDCI)
    def second_form(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        forma_pagamento = self.page.locator(':nth-child(3) > md-collapsible-header.layout-row > .md-collapsible-tools > .ng-binding')
        expect(forma_pagamento).to_be_visible()
        expect(forma_pagamento).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        self.page.locator('text=3862 - T.A.A Receber CDCI').click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3861 (T.A. A Receber A Vista)
    def cash(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        forma_pagamento = self.page.locator('text=3861 - T.A. A Receber A Vista')
        expect(forma_pagamento).to_be_visible()
        expect(forma_pagamento).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        forma_pagamento.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3865 (T.A. A Receber Futuro - Proposta)
    def proposal_credit(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        forma_pagamento = self.page.locator('text=3865 - T.A. A Receber Futuro - Proposta')
        expect(forma_pagamento).to_be_visible()
        expect(forma_pagamento).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        forma_pagamento.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3866 (T.A. A Receber Prestamista)
    def with_moneylender(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        forma_pagamento = self.page.locator('text=3866 - T.A. A Receber Prestamista')
        expect(forma_pagamento).to_be_visible()
        expect(forma_pagamento).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        forma_pagamento.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3867 (T.A. A Receber Contrato Financeira)
    def contract_finance(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        forma_pagamento = self.page.locator('text=3867 - T.A. A Receber Contrato Financeira')
        expect(forma_pagamento).to_be_visible()
        expect(forma_pagamento).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        forma_pagamento.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3868 (T.A. A Receber PIX TEF)
    def pix_tef(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        forma_pagamento = self.page.locator('text=3868 - T.A. A Receber PIX TEF')
        expect(forma_pagamento).to_be_visible()
        expect(forma_pagamento).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        forma_pagamento.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3870 (T.A. A Receber Crédito TEF)
    def credit_tef(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        forma_pagamento = self.page.locator('text=3870 - T.A. A Receber Crédito TEF')
        expect(forma_pagamento).to_be_visible()
        expect(forma_pagamento).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        forma_pagamento.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3871 (T.A. A Receber Débito POS)
    def debit_tef(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        forma_pagamento = self.page.locator('text=3871 - T.A. A Receber Débito POS')
        expect(forma_pagamento).to_be_visible()
        expect(forma_pagamento).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        forma_pagamento.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3872 (T.A. A Receber Crédito POS)
    def credit_pos(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        payment_option = self.page.locator('text=3872 - T.A. A Receber Crédito POS')
        expect(payment_option).to_be_visible()
        expect(payment_option).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        payment_option.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3873 (T.A. A Receber Cheque)
    def check(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        payment_option = self.page.locator('text=3873 - T.A. A Receber Cheque')
        expect(payment_option).to_be_visible()
        expect(payment_option).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.continue_())
        payment_option.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # ---------- Prestamista Abatimento %

    # Seleciona forma de pagamento 3874 (T.A. A Receber Futuro - para Prestamista)
    def fut_money_with_fees(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        payment_option = self.page.locator('text=3874 - T.A. A Receber Futuro - para Prestamista')
        payment_option.scroll_into_view_if_needed()
        expect(payment_option).to_be_visible()
        expect(payment_option).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        payment_option.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3875 (T.A.A Receber Presente CDCI - para Prestamista)
    def present_money(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        payment_option = self.page.locator('text=3875 - T.A.A Receber Presente CDCI - para Prestamista')
        payment_option.scroll_into_view_if_needed()
        expect(payment_option).to_be_visible()
        expect(payment_option).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        payment_option.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3876 (T.A. A Receber Futuro - para Prestamista sem juros)
    def fut_money_without_fees(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        payment_option = self.page.locator('text=3876 - T.A. A Receber Futuro - para Prestamista sem juros')
        payment_option.scroll_into_view_if_needed()
        expect(payment_option).to_be_visible()
        expect(payment_option).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.continue_())
        payment_option.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # ---------- Prestamista Abatimento Valor Fixo - 55,90

    # Seleciona forma de pagamento 3880 (T.A. A Receb Fut com juros - Prest. Valor Fixo)
    def fut_with_fees_money_reb_vf(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        payment_option = self.page.locator('text=3880 - T.A. A Receb Fut com juros - Prest. Valor Fixo')
        payment_option.scroll_into_view_if_needed()
        expect(payment_option).to_be_visible()
        expect(payment_option).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        payment_option.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3878 (T.A.A Receb Presente CDCI - Prest. Valor Fixo)
    def present_money_reb_vf(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        payment_option = self.page.locator('text=3878 - T.A.A Receb Presente CDCI - Prest. Valor Fixo')
        payment_option.scroll_into_view_if_needed()
        expect(payment_option).to_be_visible()
        expect(payment_option).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        payment_option.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # Seleciona forma de pagamento 3879 (T.A. A Receb Fut sem juros - Prest. Valor Fixo)
    def fut_without_reb_vf(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        payment_option = self.page.locator('text=3879 - T.A. A Receb Fut sem juros - Prest. Valor Fixo')
        payment_option.scroll_into_view_if_needed()
        expect(payment_option).to_be_visible()
        expect(payment_option).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        payment_option.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)

    # ---------- Prestamista Abatimento Valor Fixo - Origem Produto 99,30

    # Seleciona forma de pagamento 3881 (T.A. A Receb Fut com juros - Prest. Origem Produto)
    def fut_without_fees_reb_origin_prd(self):
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_be_visible()
        expect(self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .flex')).to_have_text('Forma de pagamento')
        botao_x = self.page.locator('.md-dialog-fullscreen > .md-primary > .md-toolbar-tools > .md-icon-button')
        expect(botao_x).to_be_visible()
        expect(botao_x).not_to_be_disabled()
        payment_option = self.page.locator('text=3881 - T.A. A Receb Fut com juros - Prest. Origem Produto')
        payment_option.scroll_into_view_if_needed()
        expect(payment_option).to_be_visible()
        expect(payment_option).not_to_be_disabled()
        self.page.route('POST', '/services/v3/pedido_forma_pagamento', lambda route: route.fulfill())
        payment_option.click(force=True)
        self.page.wait_for_response(lambda response: '/services/v3/pedido_forma_pagamento' in response.url and response.status == 200, timeout=40000)